from tkinter import*

def change_frame(x):
    print(x)
    global score
    if x==1:
        start.destroy()
        f1.pack()
        win.title('환경 시뮬레이터 Page.1')
    elif x==2:
        f1.destroy()
        f1_f.pack()
        win.title('환경 시뮬레이터 Page.2')
    elif x==3:
        f1_f.destroy()
        f1.destroy()
        f1_1.pack()
        win.title('환경 시뮬레이터 Page.3')
        score+=1
    elif x==4:
        f1_1.destroy()
        f1_2.pack()
        win.title('환경 시뮬레이터 Page.4')
    elif x==5:
        f1_2.destroy()
        f2_1.pack()
        win.title('환경 시뮬레이터 Page.5')
    elif x==6:
        f1_2.destroy()
        f2_1.destroy()
        f2_2.pack()
        win.title('환경 시뮬레이터 Page.6')
        score+=1
    elif x==7:
        f2_1.destroy()
        f2_2.destroy()
        f3_1.pack()
        win.title('환경 시뮬레이터 Page.7')
    elif x==8:
        f3_1.destroy()
        f2_2.destroy()
        f3_2.pack()
        win.title('환경 시뮬레이터 Page.8')
    elif x==9:
        f3_1.destroy()
        f3_2.destroy()
        f3_3.pack()
        win.title('환경 시뮬레이터 Page.9')
        score+=1
    elif x==10:
        f3_3.destroy()
        f3_2.destroy()
        f4.pack()
        win.title('환경 시뮬레이터 Page.10')
    elif x==11:
        f4.destroy()
        f5_2.destroy()
        f5.pack()
        win.title('환경 시뮬레이터 LAST Page')
        score+=1
    else:
        f4.destroy()
        f5.destroy()
        f5_2.pack()
        win.title('환경 시뮬레이터 Page.11')
        

win=Tk()
win.title('환경 시뮬레이터')
win.geometry('600x600')
a=PhotoImage(file='pla.png')
b=PhotoImage(file='clean.png')
c=PhotoImage(file='trash.png')
d=PhotoImage(file='earth2.png')
e=PhotoImage(file='trash2.png')

start=Frame(win,bg='white')
f1=Frame(win,bg='white')
f1_f=Frame(win,bg='white')
f1_2=Frame(win,bg='white')
f1_1=Frame(win,bg='white')
f2_1=Frame(win,bg='white')
f2_2=Frame(win,bg='white')
f3_1=Frame(win,bg='white')
f3_2=Frame(win,bg='white')
f3_3=Frame(win,bg='white')
f4=Frame(win,bg='white')
f5=Frame(win,bg='white')
f5_2=Frame(win,bg='white')

score=0

start_img=PhotoImage(file='earth.png')
lb1=Label(start,image=start_img,width=600,bg='white',height=500)
one_btn=Button(f1,text='일회용품 사용',height=13,width=250,bg='light coral',font=('consolas',15,'bold'),command=lambda:change_frame(2))
start_btn=Button(start,text='START',width=600,height=100,font=('consolas',30,'bold'),relief='solid',bg='orange',command=lambda:change_frame(1))
many_btn=Button(f1,text='다회용품 사용',width=250,bg='light skyblue',height=13,font=('consolas',15,'bold'),command=lambda:change_frame(3))
lb2=Label(f1,text='VS',width=600,font=('consolas',15,'bold'))
lb3=Label(f1_f,image=a,width=600,height=384)
end_btn=Button(f1_f,text='END',font=('consolas',20,'bold'),width=600,height=600-384,bg='orange',relief='solid',command=lambda:win.quit())
recycle_btn=Button(f1_2,text='분리수거 잘 하기',width=250,bg='light skyblue',height=13,font=('consolas',15,'bold'),command=lambda:change_frame(6))
once_btn=Button(f1_2,text='섞어서 버리기',width=250,bg='light coral',height=13,font=('consolas',15,'bold'),command=lambda:change_frame(5))
lb22=Label(f1_2,text='VS',width=600,font=('consolas',15,'bold'))
lb33=Label(f1_1,image=b,width=600,height=395)
next=Button(f1_1,text='NEXT',width=600,height=600-395,font=('consolas',30,'bold'),command=lambda:change_frame(4),relief='solid',bg='orange')
lb34=Label(f2_1,image=c,width=600,height=450)
end2_btn=Button(f2_1,text='END',font=('consolas',20,'bold'),width=600,height=600-450,bg='orange',relief='solid',command=lambda:win.quit())
lb32=Label(f2_2,image=b,width=600,height=395)
next2=Button(f2_2,text='NEXT',width=600,height=600-395,font=('consolas',30,'bold'),command=lambda:change_frame(7),relief='solid',bg='orange')
air_btn=Button(f3_1,text='에어컨 실내 적정 온도 유지하기',height=12,bg='light skyblue',width=600,font=('consolas',15,'bold'),command=lambda:change_frame(9))
whyair_btn=Button(f3_1,text='에어컨 빵빵하게 틀기',width=600,height=12,bg='light coral',font=('consolas',15,'bold'),command=lambda:change_frame(8))
lb24=Label(f3_1,text='VS',width=600,font=('consolas',15,'bold'))
lb31=Label(f3_2,image=d,width=600,height=464)
end3_btn=Button(f3_2,text='END',font=('consolas',20,'bold'),width=600,height=600-464,bg='orange',relief='solid',command=lambda:win.quit())
lb35=Label(f3_3,image=b,width=600,height=395)
next3=Button(f3_3,text='NEXT',width=600,height=600-395,font=('consolas',30,'bold'),command=lambda:change_frame(10),relief='solid',bg='orange')
small_btn=Button(f4,text='적정량만 조리하기',width=600,height=12,bg='light skyblue',font=('consolas',15,'bold'),command=lambda:change_frame(11))
big_btn=Button(f4,text='손님도 없는데 많은 양 조리하기',width=600,height=12,bg='light coral',font=('consolas',15,'bold'),command=lambda:change_frame(12))
lb26=Label(f4,text='VS',width=600,font=('consolas',15,'bold'))
lb88=Label(f5_2,image=e)
btn_end=Button(f5,text='END',font=('consolas',20,'bold'),width=600,height=600-357,bg='orange',relief='solid',command=lambda:win.quit())
lb99=Label(f5,image=b)
btn_end2=Button(f5_2,text='END',font=('consolas',20,'bold'),width=600,height=600-395,bg='orange',relief='solid',command=lambda:win.quit())

start.pack()
f1.pack()
f1_f.pack()
lb88.pack()
lb99.pack()
f1_1.pack()
f1_2.pack()
lb1.pack()
f2_1.pack()
f2_2.pack()
f3_1.pack()
f3_2.pack()
f3_3.pack()
f4.pack()
one_btn.pack()
start_btn.pack()
lb2.pack()
many_btn.pack()
lb3.pack()
end_btn.pack()
once_btn.pack()
lb22.pack()
recycle_btn.pack()
lb33.pack()
next.pack()
lb34.pack()
end2_btn.pack()
lb32.pack()
next2.pack()
whyair_btn.pack()
lb24.pack()
air_btn.pack()
lb31.pack()
end3_btn.pack()
lb35.pack()
next3.pack()
big_btn.pack()
lb26.pack()
small_btn.pack()
f5.pack()
f5_2.pack()
btn_end.pack()
btn_end2.pack()

win.mainloop()
win.quit()
window=Tk()
window.title('점수')
f=PhotoImage(file='tree.png')
n='''==Total==
    %s
  
  
  
  Best=4'''%score
text=Text(window,width=600,height=600,font=('consolas',30,'bold'))
text.insert(END,n)
text.pack()

window.mainloop()